let g:coc_global_extensions = [
  \ 'coc-actions',
  \ 'coc-sh',
  \ 'coc-lists',
  \ 'coc-emmet',
  \ 'coc-pairs',
  \ 'coc-tsserver',
  \ 'coc-floaterm',
  \ 'coc-fzf-preview',
  \ 'coc-html',
  \ 'coc-css',
  \ 'coc-yaml',
  \ 'coc-explorer',
  \ 'coc-svg',
  \ 'coc-vimlsp',
  \ 'coc-xml',
  \ 'coc-json',
  \ 'coc-marketplace',
  \ 'coc-eslint',
  \ 'coc-elixir',
  \ ]

